## NLP Deep Learning Training
### Focus:

Using Neural Networks for Text (Embedding Layer + Basic Model)

### 1. Big Picture (VERY IMPORTANT)

Until now:

👉 Text → TF-IDF → ML model

Now:

👉 Text → Embedding → Neural Network → Prediction

### Pipeline Shift
Old (Traditional NLP):
```
Text → TF-IDF → Logistic Regression
```

### New (Deep Learning NLP):
```
Text → Tokenization → Embedding Layer → Neural Network → Output
```

### 2. What is an Embedding Layer?

👉 Instead of manually creating vectors (Word2Vec),
Deep Learning learns embeddings automatically

### Idea:

Each word → converted into a dense vector inside the model

### 3. Step-by-Step Implementation

We’ll build a DL-based text classifier

### Step 1: Prepare Data

In [1]:
# Step 1: Prepare Data

texts = [
    "I love AI",
    "AI is amazing",
    "I hate spam",
    "This is spam message"
]

labels = [1, 1, 0, 0]

### Step 2: Tokenization

In [2]:
# Step 2: Tokenization

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
print(sequences)



[[1, 5, 2], [2, 3, 6], [1, 7, 4], [8, 3, 4, 9]]


### 👉 Words → numbers

### Step 3: Padding

👉 Neural networks need equal-length input

In [4]:
# Step 3: Padding

from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(sequences, padding='post')
print(X)

[[1 5 2 0]
 [2 3 6 0]
 [1 7 4 0]
 [8 3 4 9]]


### 4. Build Deep Learning Model

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=8, input_length=X.shape[1]),
    Flatten(),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


### 5. Compile Model

In [6]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

### 6. Train Model

### Step 1 — Import Libraries

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

### Step 2 — Prepare Data

In [10]:
texts = [
    "I love AI",
    "AI is amazing",
    "I hate spam",
    "This is spam message"
]

labels = [1, 1, 0, 0]

#  IMPORTANT FIX
labels = np.array(labels)   # convert list → numpy array

Why?
Neural networks understand numbers → not Python lists.

### Step 3 — Tokenization (Words → Numbers)

In [11]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
print("Sequences:", sequences)

Sequences: [[1, 5, 2], [2, 3, 6], [1, 7, 4], [8, 3, 4, 9]]


Each word now has an ID.

### Step 4 — Padding (Make Equal Length)

Neural networks need same input length.

In [12]:
X = pad_sequences(sequences, padding='post')

print("Padded Data:\n", X)

Padded Data:
 [[1 5 2 0]
 [2 3 6 0]
 [1 7 4 0]
 [8 3 4 9]]


#### VERY IMPORTANT FIX (Core Fix)

Convert X to tensor (new TF requirement):
```
X = tf.convert_to_tensor(X)
labels = tf.convert_to_tensor(labels)
```
Now both inputs are tensors

### Step 5 — Build Deep Learning Model

In [13]:
vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=8),
    Flatten(),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])

### What each layer does

| Layer     | Purpose                     |
| --------- | --------------------------- |
| Embedding | learns word meaning vectors |
| Flatten   | converts matrix → vector    |
| Dense     | learns patterns             |
| Sigmoid   | outputs spam/not spam       |

### Step 6 — Compile Model

In [14]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

### Step 7 — Train Model

In [15]:
model.fit(X, labels, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6891
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.6863
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6841
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6822
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6804
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6785
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6766
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.6749
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.6731
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.6712


Model learns quickly because dataset is tiny.

### What You Learned

This bug taught you an important DL rule:

| Before         | After         |
| -------------- | ------------- |
| Python list    |  Not allowed |
| NumPy / Tensor |  Required    |

### Pro Insight

In real projects ALWAYS convert:
```
X = np.array(X)
y = np.array(y)
```
or
```
tf.convert_to_tensor()
```

### 7. Prediction


In [16]:
test = ["AI is powerful"]

seq = tokenizer.texts_to_sequences(test)
pad = pad_sequences(seq, maxlen=X.shape[1])

pred = model.predict(pad)

print("Positive" if pred[0] > 0.5 else "Negative")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
Positive


### 8. Understanding Each Layer

###  Embedding Layer

👉 **Converts** word index → dense vector

👉 **Learns** meaning automatically during training


### 9. ML vs Deep Learning (Clear Difference)

| Feature               | ML (TF-IDF) | Deep Learning    |
| --------------------- | ----------- | ---------------- |
| Feature engineering   | Manual      | Automatic        |
| Context understanding | Low         | Better           |
| Performance           | Good        | High (with data) |

### 10. Critical Thinking

👉 Question:

Why does Deep Learning perform better when:

### Dataset is large?

Deep learning performs better on large datasets because neural networks require a large number of examples to learn meaningful patterns, reduce overfitting, and adjust millions of parameters effectively. With more data, the model generalizes better and becomes more accurate on unseen inputs.

### Practice Tasks
### Task 1:

Change:
```
output_dim=16
```
👉 Observe performance change

### Task 2:

Increase:
```
epochs=20
```
###  Task 3:

Add more sentences (at least 10)

### STEP 1 — Add More Sentences (Task 3 first)

We increase dataset (VERY IMPORTANT for DL)

In [22]:
#  More training data = better learning
texts = [
    "I love AI",
    "AI is amazing",
    "I hate spam",
    "This is spam message",

    # ➕ Added 10 more sentences
    "Machine learning is powerful",
    "Deep learning is the future",
    "Spam messages are annoying",
    "I enjoy learning Python",
    "Artificial intelligence is smart",
    "This message is spam",
    "I love data science",
    "Free money offer is spam",
    "Neural networks are strong models",
    "This is a normal message",
    "AI helps in automation",
    "Spam emails should be blocked"
]

labels = [
    1,1,0,0,
    1,1,0,1,1,0,1,0,1,0,1,0
]

### STEP 2 — Tokenization + Padding

In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

# Make all sequences equal length
X = pad_sequences(sequences, padding='post')

labels = np.array(labels)   # FIX: convert to numpy array

### STEP 3 — Model (Task 1: Change embedding size)

#### IMPORTANT CHANGE:

We change:
```
output_dim = 16   # was 8 before
```

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16),  #  TASK 1 CHANGE
    Flatten(),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

### STEP 4 — Compile Model

In [20]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

### STEP 5 — Train Model (Task 2: epochs=20)

In [21]:
model.fit(X, labels, epochs=20)   #  TASK 2 CHANGE

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6943
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5625 - loss: 0.6899
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6875 - loss: 0.6859
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 0.6821
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.6786
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.6752
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7500 - loss: 0.6720
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8750 - loss: 0.6688
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8750 - loss: 0.6656
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8750 - loss: 0.6622
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8750 - loss: 0.6587
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8750 - loss: 0.6550
Epo

## Now let’s understand what you changed

### TASK 1 — Why increase output_dim=16?
Before:
```
output_dim = 8
```
After:
```
output_dim = 16
```
#### Meaning:
- Each word is represented with more features
- Model learns richer meaning of words

#### Simple idea:
| Dimension | Meaning                       |
| --------- | ----------------------------- |
| 8         | basic word understanding      |
| 16        | deeper semantic understanding |


✔ Better representation

❌ But more computation

### TASK 2 — Why increase epochs=20?
Before:
```
epochs = 10
```
Now:
```
epochs = 20
```
Meaning:

Model sees dataset 20 times

✔ Learns better patterns

✔ Improves accuracy

❌ Too many epochs can cause overfitting

### ASK 3 — Why add more sentences?

Deep learning rule:

👉 More data = better learning

Before:
- 4 sentences ❌ (too small)

After:
- 16 sentences ✔ (better)

Effect:
- model sees more spam patterns
- improves generalization
- reduces overfitting

### Final Summary

You improved your model in 3 ways:

| Change        | Effect                |
| ------------- | --------------------- |
| output_dim=16 | richer word meaning   |
| epochs=20     | deeper training       |
| more data     | better generalization |

Real-World Insight

This is EXACTLY how AI engineers improve models:

👉 Step 1: increase data

👉 Step 2: improve embeddings

👉 Step 3: train longer

👉 Step 4: observe metrics